### ISSUE TITLE
Add focus ring

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/o-buttons#113]
Requested by @lc512k 
> Hi folks. It’s been raised a few times in the dev team that our buttons focus state is a color change alone, and it’s hard to distinguish if you’re navigating quickly throughout the site (also breaking “don’t use color alone to convey info” guideline https://www.w3.org/WAI/gettingstarted/tips/designing.html#dont-use-color-alone-to-convey-information)

> Could we look into adding an additional indication of focus, like a focus ring or other options? (One example I find very nice is what Github are doing. See New button in https://github.com/Financial-Times/)

cc @oliver.powell

**Comment by olipowell** [comment]
Sounds good to me! Are we able to use alpha, like the GitHub focus?

**Comment by onishiweb** [comment]
Sure, definitely possible to do this, especially with the new o-colors major.
