### ISSUE TITLE
Legibility for standout button w/disabled attribute

### ISSUE THREAD

**Issue by andygout** [Financial-Times/o-buttons#114]
Styling applies `color: #17484C` when `.o-buttons--standout` has `disabled` attribute.

Perhaps better from accessibility/legibility perspective to leave white (as text is when not in `disabled` state).

#### Current:
![screen shot 2017-04-26 at 13 10 23](https://cloud.githubusercontent.com/assets/10484515/25435156/094a45cc-2a87-11e7-8c4b-85aa7ee03045.png)

#### Suggestion:
![screen shot 2017-04-26 at 13 45 24](https://cloud.githubusercontent.com/assets/10484515/25435162/0d04a8d8-2a87-11e7-8c88-75029565727b.png)

**Comment by alicebartlett** [comment]
Yep this looks like a bug actually.
