### ISSUE TITLE
Colour changer

### ISSUE THREAD

**Issue by olipowell** [Financial-Times/o-buttons#115]
As previously discussed, the current button palette is a little restrictive so hacks need to be done to change their colours. Not a bad thing, just wonder if there's a better way.

A colourizer button would be ace!

**Comment by alicebartlett** [comment]
Oli, not sure I understand what you're asking for here. Could you add some more detail to the issue please?

**Comment by olipowell** [comment]
Sure. We have a few buttons flying about that have different colors to o-buttons for various reasons. We tried updating the inverse theme to add variety, but it's not quite enough and wonder if this can be done within Origami to make the process proper. An idea was to have one button (possibly inverse theme) that could take on different colors.

<img width="369" alt="screen shot 2017-06-20 at 10 24 19" src="https://user-images.githubusercontent.com/24250602/27326170-ab6d453e-55a2-11e7-8f54-e8b9670a305e.png">

**Comment by alicebartlett** [comment]
Ah, so this would be an update where you can pass an o-colors color in to the oButtons mixin and it will output a button?
Eg oButtons('lime')

**Comment by olipowell** [comment]
That would be ideal. I suppose it could get complicated with the various states but perhaps we could utilize the tint function.

**Comment by alicebartlett** [comment]
this has been done! #126
