### ISSUE TITLE
focus state

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-buttons#119]
seems permanent when clicking on buttons. Any button in the registry demo at the moment keeps a vestige of the teal border.

**Comment by JakeChampion** [comment]
That's correct, when clicking a button, the button becomes focused.

You can see this on github.com by clicking on a button, moving your cursor off the button and then releasing the click. 
![screen shot 2017-06-07 at 16 27 31](https://user-images.githubusercontent.com/1569131/26886784-38f7c104-4b9e-11e7-9958-0d0cfee2e1d8.png)
I don't think there is much we can do to stop this from happening as it is how browsers behave.

**Comment by gvonkoss** [comment]
mmmm. Possibly a weird next thing then, which looks like this atm:
![screen shot 2017-06-07 at 17 17 47](https://user-images.githubusercontent.com/16777943/26889198-42db9216-4ba5-11e7-94b7-8fd57e0f5f78.png)
So I'll be looking for the fix elsewhere (:
