### ISSUE TITLE
Mixins/placeholders to retrieve button typography or bg styles independently

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-buttons#12]
For the responsive article we have a round button done with svg. So I don't need the bg styles, but would still like a way to get hold of the typography for the kind of button it imitates (in this case it's --standout). So a mixin or placeholder class to extend would be handy.

I can't think of a use case for the opposite - retrieving the bg & layout styles without the typography - but might be worth adding too.

**Comment by kaelig** [comment]
You can use `$o-buttons-font-family` (v2 only) and `@include oButtonsSize(big);` (v1).

Feel free to re-open if there are still issues with that.
