### ISSUE TITLE
update to hover and active states

### ISSUE THREAD

**Issue by olipowell** [Financial-Times/o-buttons#120]
o-tabs has highlighted the new active state for o-buttons is not right. Propose we use a less severe color such as `teal-30` to fix this. Sketch has been updated to reflect the changes.

Also, Inverse and Mono hovers are slightly different to the designs 😔

**Comment by alicebartlett** [comment]
This would be a good issue for our new starter in August.

**Comment by alicebartlett** [comment]
![buttons-artboard](https://user-images.githubusercontent.com/68009/29627374-d012ccf6-8829-11e7-983b-7653e457f607.png)

**Comment by notlee** [comment]
Corrected in v5.1.1 https://github.com/Financial-Times/o-buttons/releases/tag/v5.1.1 🎉
