### ISSUE TITLE
inverse-primary theme?

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/o-buttons#124]
we're using something along these lines for the App's login screen:

![screen shot 2017-07-13 at 12 46 04](https://user-images.githubusercontent.com/631757/28164877-4ff0d0d4-67c9-11e7-95ec-1702935fb1cf.png)

using these styles (which probably aren't ready to fold into o-buttons, so this isn't yet a PR):

```scss
$o-buttons-themes: map-merge($o-buttons-themes, (
	inverse-primary: (
		normal: (
			color: black,
			background-color: white,
			border-color: transparent,
		),
		active: (
			border-color: oColorsGetPaletteColor(teal-80),
		),
		hover: (
			color: oColorsGetPaletteColor(teal-40),
		),
		pressedselected: (
			color: white,
			background-color: rgba(white, 0.4),
			border-color: white,
		)
	)
));
```

is this something that you'd like to bring into o-buttons?

**Comment by alicebartlett** [comment]
Hi! I'm working on a similar problem. I'm going to try and add something to o-buttons that works for both of us. I'll tag you when it's shipped.

**Comment by alicebartlett** [comment]
@quarterto we shipped this! It's a mixin.
#126

**Comment by quarterto** [comment]
lovely, thanks! just checking, my use case would be `@include oButtonsCustomTheme('teal', 'white', primary)`?

**Comment by alicebartlett** [comment]
Yes, only, looking at your picture again, the text colour would be teal not black. So you probably want to override that :-/
