### ISSUE TITLE
Use custom themes for mono and inverse buttons

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-buttons#125]
Mono and inverse buttons should use [custom themes](https://github.com/Financial-Times/o-buttons/pull/126), but this isn't possible without a breaking change as it requires us to restrict the background that those buttons can appear on. Also we'd need to remove all of the colour use-cases for these themes, which could constitute a breaking change for anybody who's overriding them.

**Comment by notlee** [comment]
Using custom theme functionality would be good so we are using the same functionality we offer to users. However to remove transparency we can now update the mono/inverse buttons in brand configuration: https://github.com/Financial-Times/o-buttons/pull/157/files#diff-07836e80eaaf110553a25f5ae1906f34R39

**Comment by notlee** [comment]
This will be possible in the next major release 🎉 see https://github.com/Financial-Times/o-buttons/issues/205
