### ISSUE TITLE
Add warning icon to buttons

### ISSUE THREAD

**Issue by ajwl** [Financial-Times/o-buttons#132]
Hello,
Can we add the "warning" icon to the range of button icons available? 
This is the variable that I believe needs the value "warning" added to it: 
https://github.com/Financial-Times/o-buttons/blob/9b082b0b07a67846195010a17a8c959f380ed880/scss/_variables.scss#L79

This is the warning exclamation point icon we'd like added in 
http://registry.origami.ft.com/components/fticons

thanks origami

**Comment by alicebartlett** [comment]
Done!
