### ISSUE TITLE
Make available a 'marketing' style button

### ISSUE THREAD

**Issue by geek-caroline** [Financial-Times/o-buttons#144]
A 'marketing button' is [already used in o-banners](https://github.com/Financial-Times/o-banner/blob/master/src/scss/themes/_marketing-primary.scss#L21), it should probably be made available as a standard button style in o-buttons.  @rowanmanning and @draysonandstock know more about this

In the interests of being pragmatic, I have copy and pasted the same style of button and colours into [my code in n-ui](https://github.com/Financial-Times/n-ui/blob/master/components/n-ui/header/scss/_marketing-promo.scss#L1) to enable this button style in the promo banner.
![This is the button in situ in my n-ui code](https://user-images.githubusercontent.com/1362205/32558637-262aeb64-c49d-11e7-87ed-cffc63ce7c3b.png)

I would very much like to delete this copy-paste code and put the proper type of button in place if this is possible.

**Comment by rowanmanning** [comment]
Could we maybe wait on this until we know what's happening with the new button styles that @draysonandstock is working on? Based on his designs, this style will just become the default "primary" and so other o-buttons work would be needed.

As discussed, if we added this into o-buttons now then we'd need to deprecate `o-buttons--b2c` and add in two new themes: `o-buttons--marketing-primary` and `o-buttons--marketing-secondary`

**Comment by notlee** [comment]
I believe this is taken care of by bringing the mono theme to the primary button. 
https://registry.origami.ft.com/components/o-buttons@5.11.1#demo-primary-button-mono

Let me know if I'm mistaken. :)
