### ISSUE TITLE
Selected and disabled states on Standout buttons 

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#15]
Currently the standout buttons have the same selected and disabled states as the default buttons.

Could we change these so that:

* a selected standout button is perhaps darker/brighter blue
* the default appears to be a muted blue with a white labels (see disabled state of Bootstrap's primary buttons).

**Comment by kaelig** [comment]
This was added in 1.7.

See the latest demos: http://build.origami.ft.com/files/o-buttons@1.8.1/demos/individual-standout.html
