### ISSUE TITLE
Add a primary state for Inverse and Mono themes.

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-buttons#152]
To add a primary state for Inverse and Mono themes as these are now being used more to provide the correct level of contrast on coloured backgrounds across FT.com. It also provides a complete set of buttons for any white label products. 

I've checked the contrasts but would be good to check these in Pa11y as we might need to make some adjustments. 

Also i've used Slate instead of Black but would be good to see how this works and whether we should use 100% black. 

Sketch file is 'o-buttons' within 'components ' in FT Design. The below image is just for reference. 

<img width="396" alt="screen shot 2018-02-23 at 13 46 37" src="https://user-images.githubusercontent.com/11214093/36599974-e6adef6c-18a8-11e8-8c6f-047cc52e7bd0.png">

**Comment by notlee** [comment]
Primary inverse: https://github.com/Financial-Times/o-buttons/pull/155
Primary mono: https://github.com/Financial-Times/o-buttons/pull/163
