### ISSUE TITLE
Add :focus styling to customised buttons

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-buttons#153]
The mixin [`oButtonsCustomTheme`](https://github.com/Financial-Times/o-buttons/blob/a646b58fe9a7145a7004a72049b339ffe0f9c930/scss/_mixins.scss#L100) doesn't style `:focus`, which currently defualts to a transparent background and `teal` text color & outline.

**Comment by notlee** [comment]
This has been resolved here: https://github.com/Financial-Times/o-buttons/pull/157
