### ISSUE TITLE
Review custom button focus state.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-buttons#167]
The focus state of a custom button relies on an outline rather than a colour change (unlike all of our pre-defined buttons e.g. primary, mono, inverse, etc.). What should the custom button focus state look like?

This issue is demonstrated here, note in the second .gif the focus states of the first three cards (custom buttons) vs. the final card (pre-defined button, mono):
https://github.com/Financial-Times/o-subs-card/pull/16

**Comment by rowanmanning** [comment]
Covered by another issue
