### ISSUE TITLE
More buttons colours

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#18]
I have a message box displayed to the user. It could be an infobox or something using the severity palette.

I would have thought these buttons should be a similar colour to the background. Perhaps a darker shade of that colour.

For example a buttons inside an Infobox (with a yellow background) should be some kind of yellow. At the moment I can only choose pink (default) or blue (standout).

Could we do something like this instead:

```html
<div class="infobox">
   <p> message</p>
   <button class="o-ft-buttons o-ft-buttons--infobox">Selected</button>
</div>
```
or

```html
<div class="message-box-severity2">
   <p> message</p>
   <button class="o-ft-buttons o-ft-buttons--severity-2">Selected</button>
</div>
```

**Comment by kaelig** [comment]
Since that issue was opened, a series of colors have been added.

Products may tweak these colors if they have a good reason to do it. If a use case comes back often we'll consider adding new themes to the module.

**Comment by kavanagh** [comment]
Actually this is fulfilled by bg and border transparency.
