### ISSUE TITLE
A few additions to o-buttons. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-buttons#183]
A couple of updates to o-buttons. 

- [ ] Can we also enable icons to be positioned to the right of the button text. 

- [x]  Can we add an Upload [with the icon]. This completes the pair of icon buttons as we currently have an upload option. 

- [x]  A defined rule for how we handle tints for the various states of Custom buttons. The pink/claret buttons in the Sketch file. 

- [ ]  Adding a positive (Jade) and Dangerous (Crimson) button themes for both Masterbrand and Internal Products as this allows for major decisions or none reversible ones to be communicated better to the user. 

- [ ]  Introduce a Ghost button style for Masterbrand, Mono and Inverse themes. I've got an alternative version for the Masterbrand as it would be good to check accessibility of both options. **Edit: Moved here https://github.com/Financial-Times/o-buttons/issues/194**

Sketch file is here https://drive.google.com/file/d/1xiQaAu6o1Kkj2SK0cojsvkxJKmZBZGwl/view

Ask me if you have any questions. James

**Comment by notlee** [comment]
Adding icons: https://github.com/Financial-Times/o-buttons/pull/185

**Comment by rowanmanning** [comment]
TODO break this out into separate issues. @notlee?

**Comment by notlee** [comment]
> A defined rule for how we handle tints for the various states of Custom buttons. The pink/claret buttons in the Sketch file.

This will be the case in the [next major](https://github.com/Financial-Times/o-buttons/pull/208). The design team are adding the updated colours to a Sketch UI Kit. 

I've opened separate issues for outstanding updates:
- https://github.com/Financial-Times/o-buttons/issues/194
- https://github.com/Financial-Times/o-buttons/issues/210
- https://github.com/Financial-Times/o-buttons/issues/211
