### ISSUE TITLE
Add refresh button

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/o-buttons#188]
It'd be great to have a button which indicates to a user that they can re-do an action which has just happened.  My usecase is a list of validation errors, with a button which allows someone to re-run the validation.
![image](https://user-images.githubusercontent.com/428847/47306286-e80a7900-d623-11e8-82ec-03c3bcdff348.png)

**Comment by rowanmanning** [comment]
@lucas42 do you still need something like this? You can currently do this with a manual local build, but not with the Build Service. We're doing some issue cleanup so I'm going to close for now but we can reopen if needed.

**Comment by lucas42** [comment]
We're currently hardcoding a workaround in our CSS: https://github.com/Financial-Times/monitoring-manager/blob/2cffbcebac18a2a52b09d249631b2b35f98f97ef/public/index.css#L63

I'm in no hurry to do anything about it, but I don't think that approach is ideal.
