### ISSUE TITLE
Big red button

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-buttons#191]
At least for the internal brand, it'd be good to have a 'danger' themed button e.g. to distinguish between save and delete buttons. 

This github issue exemplifies it well 

![image](https://user-images.githubusercontent.com/447559/48482267-243a8f00-e808-11e8-988b-c346fe5ac479.png)

**Comment by notlee** [comment]
Sensible! Is it a style of button you've started using already with a custom button?

**Comment by rowanmanning** [comment]
This will hopefully be covered when @notlee splits out #183 into separate issues. He'll link to the new issue when it's open.
