### ISSUE TITLE
Improve accessibility of button disabled state

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-buttons#200]
Our recent accessibility audit highlighted some accessibility issues, including the contrast of disabled button states.

See the [audit on Google Drive](https://drive.google.com/file/d/0BxB2_i9bsGTpOWhzckxMVjBwMmdSNGc0YkpSd2RYUjRLWWJr/view).

**Comment by rowanmanning** [comment]
This one is an odd one. According to the guide that @notlee found, disabled things don't need to have high contrast according to WCAG, and the solution we came up with was to just remove disabled pagination buttons. We'd need some design input onto what higher-contrast disabled buttons if we decide to do this.

**Comment by nickcolley** [comment]
In terms of technicality of WCAG they dont count as contrast issue:

>  are part of an inactive user interface component,

https://www.w3.org/TR/WCAG21/#contrast-minimum

We should consider WCAG as the minimum we want to achieve and not restrict us from going beyond it.

So as we know that disabled buttons are not very usable, I think the correct approach is what [Lee has done by updating the guidance](https://github.com/Financial-Times/o-buttons/pull/262).

Which is to make it clear that you should avoid disabled buttons and use other methods instead:

https://github.com/Financial-Times/o-buttons#disabled

**Comment by notlee** [comment]
thanks @nickcolley :)
