### ISSUE TITLE
Right align button icons

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-buttons#210]
Button icons are always aligned to the left. Having a modifier class to have the option to align icons to the right [has been requested](https://github.com/Financial-Times/o-buttons/issues/183). Find out if this is still needed.

**Comment by JakeChampion** [comment]
I've asked in [#desig-ops](https://financialtimes.slack.com/archives/C01481FKWA2/p1607967039200800) if we use buttons with right-aligned icons 👍

**Comment by JakeChampion** [comment]
>Find out if this is still needed.

Maybe Markets Data? It is using o-buttons though.
![image](https://user-images.githubusercontent.com/1569131/102205420-12ce8000-3ec3-11eb-8589-679e698f57e9.png)

**Comment by notlee** [comment]
That's far from Origami or o-buttons, they'd probably be their own component if we did standardise them. A request for right aligned icons has come up a few times over the years. The only example I can find is [this request for right aligned icons](https://financialtimes.slack.com/archives/C02FU5ARJ/p1530720299000010), and the conclusion was that it doesn't really matter and they can stay left aligned 🤷 

Let's close this issue unless design ops think it's worth adding proactively?
