### ISSUE TITLE
Buttons issues on IE11

### ISSUE THREAD

**Issue by bbcreatv** [Financial-Times/o-buttons#232]
## What
Buttons on IE11

## Details

- Text is not aligned properly
- Icons do not display correctly
- Describe the environment you are having this problem in
	- IE11 Windows 10

![image](https://user-images.githubusercontent.com/3500928/74023027-fc03f680-499e-11ea-9337-8c49895f5f23.png)

**Comment by rowanmanning** [comment]
Thanks for reporting! We're on this, and have fixed the text-alignment issue: #233. We'll fix the other issues as separate PRs.

**Comment by rowanmanning** [comment]
I think this is all fixed in v6.0.8. Thanks again!
