### ISSUE TITLE
Edge 80 - border radius

### ISSUE THREAD

**Issue by bbcreatv** [Financial-Times/o-buttons#237]
## What

Edge 80 has a default border radius of 2px
## Details

Just noticed while testing - the new Edge 80 (latest) has a default border radius of 2px on buttons
Also tested on Edge 81 (Dev) and its the same

![image](https://user-images.githubusercontent.com/3500928/74922884-2d81b680-53d0-11ea-841f-786d211b40a1.png)
![image](https://user-images.githubusercontent.com/3500928/74923090-82253180-53d0-11ea-8167-4b454e8a6905.png)

**Comment by notlee** [comment]
Thanks for the heads up, we'll remove that! (it's actually not a bad look)

**Comment by bbcreatv** [comment]
Yeah, and Edge had to be different in some way 😄
