### ISSUE TITLE
Improve active state

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-buttons#247]
Our buttons do not give feedback when clicked as shown in the attached gif. That’s because the hover state takes precedence over the active state, so the active state isn’t shown until the cursor is moved away. The lack of feedback is a pretty bad experience when using buttons to interact with a page.

![mono-current-active-state](https://user-images.githubusercontent.com/10405691/79315199-90885900-7efa-11ea-99b9-c82708f3ea27.gif)

For an intimidate improvement, make the active state take precedence over the hover state so we give that immediate feedback. The drawback here is an active button then has no hover state.  Follow up with product design on what an active + hover state looks like for primary and secondary buttons.

**Comment by notlee** [comment]
>For an intimidate improvement, make the active state take precedence over the hover state so we give that immediate feedback:

I've asked for any objects in the design slack channel here:
https://financialtimes.slack.com/archives/C8U9J5YJ2/p1586938440081500

**Comment by notlee** [comment]
The active state in v5 and v6 now takes precedence over the hover state.

Keeping this open for now as I think we should have an active+hover state so users know when they are interacting with an active button.

**Comment by josh-wade-ft** [comment]
I would try reducing the button opacity by `20%` on `:active` state - to provide immediate feedback without clashing with other states

**Comment by notlee** [comment]
hey, sorry I dropped this after asking for input

We updated o-buttons to give instant feedback on click (when the button is "active").
For example the primary button immediately gets darker:
![Kapture 2020-07-15 at 10 19 07](https://user-images.githubusercontent.com/10405691/87528050-e8169c00-c684-11ea-849b-9a2ea7bbf37a.gif)

However when a button has been pressed there is no feedback on hover.
I.e. there's no active+hover state. We could try darkening again to indicate an
active plus+hover state. It almost makes the button black though and isn't all 
that noticeable. Here's a demo with the primary button again:
![Kapture 2020-07-15 at 10 20 16](https://user-images.githubusercontent.com/10405691/87528416-66733e00-c685-11ea-89c0-8627692ae260.gif)

It might be we don't need to indicate when an active button is hovered beyond the 
standard cursor change. I notice neither [Bootstrap](https://v5.getbootstrap.com/docs/5.0/examples/), [Carbon](https://www.carbondesignsystem.com/components/button/code/), [Rizzo](https://rizzo.lonelyplanet.com/styleguide/ui-components/buttons#) have a focus+active 
state on their buttons. [GDS](https://govuk-elements.herokuapp.com/buttons/) do have a focus+active state but not using colour, the 
button depresses when active.

**Comment by notlee** [comment]
Chatting with Luke we've decided not to add a hover+active state at the moment but are open to revisiting if we find a use case. The only button we could find that uses a hover+active state at the moment is the "add to myft" button, which is not part of o-buttons.
