### ISSUE TITLE
Add disabled button state guidelines to README.md

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-buttons#256]
- they may be used, and it's ok that their contrast is low
- but they should be avoided at all cost in favour of different ux
see https://financialtimes.slack.com/archives/C2LMEKC6S/p1589799098017100

**Comment by nickcolley** [comment]
Good tweet from Adam here which shows how keeping a button enabled allows you to give clear feedback why the user cannot continue instead of a brick wall interfaction.

https://twitter.com/adambsilver/status/1170954800374173696
