### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#30]
This is a single button that is either "on" or "off".

We'll use the `aria-pressed="true"` state to define a buttons as *pressed*/*on*.

`aria-pressed="false"` means *off*. 

The two examples below are not equivalent, in that the absence of the `aria-pressed` attribute does not mean that button is in the off state.

```html
<button aria-pressed="false"></button>
<button></button>
```
This helps use visually to differentiate between a regular button and a button that is pressable and currently in the off state. This is needed so the user understand what will happen before they click the button.

Note there is an important distinction between *selected* and *pressed*. The selected state would be used in a button group scenario. Pressed would be used in a single toggleable button.

Also note that primary buttons would never have a `aria-pressed` attribute. Same is true for "danger" and "success" buttons that may be introduced soon (tbc).

Specific design details to follow. Let's start with functionality.

**Comment by kaelig** [comment]
Shouldn't an "on/off" control be a form element (checkbox?)?

**Comment by kavanagh** [comment]
Good point. Probably. Could we have both? Either way you get the green button. Choice of markup is developer/product option.

**Comment by kaelig** [comment]
I guess it's doable using something like 

```scss
.my-input:checked + label {
  @include oButtons(medium);
}
```

And then you'd add the desired aria attribute to the label (althought it's a bit weird).

**Comment by kaelig** [comment]
I've added some code in demos to show how to do this easily:

```js
var switchState = function(element, state) {
	element.setAttribute(state, (!element.getAttribute(state) || element.getAttribute(state) === 'false' ? true : false));
};

document.addEventListener('click', function(e) {
	if (e.target.className.includes('o-button')) {
		if (!e.target.getAttribute('aria-pressed') &&
			e.target.getAttribute('aria-disabled') !== 'true') {
			switchState(e.target, 'aria-selected');
		}
		if (e.target.getAttribute('aria-pressed')) {
			switchState(e.target, 'aria-pressed');
		}
	}
	e.stopPropagation();
}, false);
```

Feel free to reopen if that's not showing it clearly enough.
