### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#32]
![image](https://cloud.githubusercontent.com/assets/684559/3997205/6530857a-293d-11e4-8c04-9dff008db0e8.png)

Registering this issue on o-ft-buttons as a placeholder.

I'd prefer this to be a standalone component.

We all know roughly what they look like and how they work so I suggest we get something made and then tweak the designs.

I think we'll need to give developers examples to help with usage when choosing between a switch, checkbox and toggle button.

Discussion note about usage: switch actions are applied immediately and are easily reversible, unlike a check box in a form that might not change state until after a submit button is pressed and may not be reversible (like agreeing to Terms and Conditions when signing up for a service).

**Comment by kaelig** [comment]
Not sure this should be part of the button module. It's probably more of an advanced checkbox style. Closing for now, feel free to make a new component if you need one in your projects.
