### ISSUE TITLE
Line height is too big

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#55]
See screenshot

![seat_moves__uk_parliament_seat_projection](https://cloud.githubusercontent.com/assets/684559/6640853/f72bee0c-c991-11e4-8126-5ab80221231c.png)

**Comment by kavanagh** [comment]
Unfortunately `line-height` is used to set the height of the button.

**Comment by kaelig** [comment]
Can you please propose a fix where the height would be set using `padding`+`line-height` (instead of `line-height` only)?

(+ add multiline buttons to the test demo)

**Comment by kaelig** [comment]
I'm going to have a look at it for the v2

**Comment by kavanagh** [comment]
Cheers/Phew. Changing this while ensuring (single deck) buttons are same height as form fields sounds a bit fiddly.

**Comment by kaelig** [comment]
@kavanagh I have a secret sauce: https://github.com/Financial-Times/o-buttons/blob/line-height/scss/_mixins.scss#L15

Let me know what you think :)

**Comment by kavanagh** [comment]
And input[type=text] would use the same?

**Comment by kaelig** [comment]
That's a good idea. There are some weird things that browsers do with text inputs so it might have to be slightly more complex, but I'll look into it.
