### ISSUE TITLE
Merge this into o-forms

### ISSUE THREAD

**Issue by kavanagh** [Financial-Times/o-buttons#56]
Lots of similarities with o-forms. And buttons are often used with forms.

**Comment by kavanagh** [comment]
As discussed on [o-forms/#69](https://github.com/Financial-Times/o-forms/issues/69)

**Comment by AlbertoElias** [comment]
I don't agree, I think you use buttons a lot more than forms, and forms is quite a big module, so adding it entirely just to get the buttons doesn't sound ideal. Also, I don't think many people will go to the registry and find buttons in the forms module, there is a connection, but not enough imo for people to think that they'll get button in o-forms

**Comment by kavanagh** [comment]
> forms is quite a big module

Is it really that big? Maybe o-buttons is a stovepipe module.

> I don't think many people will go to the registry and find buttons in the forms module.

Isn't that a discovery/search problem? Does the registry use the component name, description and keywords for the search (or just the name)?

**Comment by kaelig** [comment]
@kavanagh forms is about 10KB (3KB gzipped), that's a lot of code

**Comment by kavanagh** [comment]
Why is o-forms so big!?

How'd you work out the size, from the output of the build service? That's not necessarily a reason not to do it. Isn't bower use more common anyway?

Also what about this...?

```sass
o-forms-simple-inputs-is-silent: true;
o-forms-buttons-is-silent: false;
o-forms-advanced-stuff-is-silent: true;
```

**Comment by kaelig** [comment]
@kavanagh o-forms contains a few icons inlined in base64 in the CSS, so that's a few lines of code.

Feature flags for modules are a very interesting thought! Although I'm concerned it could add a documentation/deprecation process overhead. I'm all for micro optimisation but I'd like to see how other products use it before we embed too much granularity.

**Comment by kaelig** [comment]
> How'd you work out the size, from the output of the build service?

Yes, from the output of the build service

**Comment by kaelig** [comment]
Closing as we think o-forms and o-buttons should be separate.
