### ISSUE TITLE
Normal button style is a bit wishy-washy

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-buttons#70]
It feels like the ordinary button style fades in to the background a little too much. Also lacking a little in affordance. Can we either a) beef it up a bit or b) add an intermediate button style between normal and standout. When attempting to make an engaging form with more than a single submit button it feels like there's very little room for manouevre

**Comment by AlbertoElias** [comment]
Could you assign it to a designer?

**Comment by pauloneillft** [comment]
The D&UX team will be doing a style audit/ branding workshop for Next. In it I hope we can firm up on button styles. FWIW the display of buttons hasn't come up with any usability issues in any testing to date. 

@wheresrhys are you using buttons correctly (although I understand if the styleguide may not be clear). Dan skinner's original modal was that the "Call-to-action" Buttons or stand-out buttons are supposed ot be used for affirmitive actions on the page. For example on a form postcode lookup in standard but submit form in stand out style.

**Comment by wheresrhys** [comment]
I raised the issue mainly on the back of this 
![image](https://cloud.githubusercontent.com/assets/447559/12976542/c343e256-d0bc-11e5-8a57-b9d57f442aec.png), which felt not call-to-actiony enough, though using the standout style was too much.

What usability testing has been done on buttons?

**Comment by alicebartlett** [comment]
Closing this because as @pauloneillft says:

> FWIW the display of buttons hasn't come up with any usability issues in any testing to date.
