### ISSUE TITLE
Accessible colors

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/o-buttons#83]
see https://app.frontify.com/d/5GC1Squ8FMrZ/next-style-guide#/basics/buttons

**Comment by mariabg** [comment]
With the new colours pa11y was returning more errors. In this document I pointed at the errors, and propossed some changes:
https://docs.google.com/a/ft.com/presentation/d/1JaFMdcKZSheFARSS5s73C1UPqeEsgIOi5nkPs7DjMq8/edit?usp=sharing

**Comment by mariabg** [comment]
With the new colours Pa11y test is not failing, so I'll close this issue!
