### ISSUE TITLE
Possible ie9 design regression

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-buttons#88]
![image](https://cloud.githubusercontent.com/assets/447559/17209589/aeae15fa-54b5-11e6-9e7a-4a555ba22e7d.png)

I've not noticed the white dots in the corners til recently

**Comment by mariabg** [comment]
Sorry for the delay, it should be fixed now, @wheresrhys. Thanks!
![screen shot 2016-09-13 at 16 20 13](https://cloud.githubusercontent.com/assets/3081639/18479764/1f956ec0-79ce-11e6-879f-4b55f488276d.png)

**Comment by mariabg** [comment]
#95
