### ISSUE TITLE
Give Standard Button a more prominent focus style

### ISSUE THREAD

**Issue by lc512k** [Financial-Times/o-buttons#99]
Focused states for most o-buttons are great in that they make it very evident for the user when the button has gained focus, such as B2B and Individual styles:

B2B
<img width="251" alt="screen shot 2016-11-24 at 11 35 39" src="https://cloud.githubusercontent.com/assets/3425322/20597254/8bad4c64-b23a-11e6-8ab2-5c92d49b246c.png">
<img width="291" alt="screen shot 2016-11-24 at 11 35 39" src="https://cloud.githubusercontent.com/assets/3425322/20597238/7677eb1a-b23a-11e6-8104-deeb5a8a08f6.png">

Individual:
<img width="291" alt="screen shot 2016-11-24 at 11 34 03" src="https://cloud.githubusercontent.com/assets/3425322/20597237/7677132a-b23a-11e6-8bb7-e8f8501a1a09.png">

But the Individual-Standout style is different, in that only the focus ring is apparent, with no evident color changes to the button. This can make it difficult for the user to pick up that the button has been selected:

Individual-Standout:
<img width="306" alt="screen shot 2016-11-24 at 11 33 51" src="https://cloud.githubusercontent.com/assets/3425322/20597239/767b1bbe-b23a-11e6-8203-e37b557d347f.png">

**Comment by lc512k** [comment]
Came back as an AA issue in the DAC report 
<img width="476" alt="screen shot 2016-12-09 at 11 07 47" src="https://cloud.githubusercontent.com/assets/3425322/21047103/fa77ae34-bdff-11e6-9937-0cdbc8bbce06.png">

**Comment by alicebartlett** [comment]
#101
